/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    CmsControlPanel: typeof import('./src/components/cms-controls/CmsControlPanel.vue')['default']
    ElementResolverComponent: typeof import('./src/components/elements/ElementResolverComponent.vue')['default']
    ImageElementComponent: typeof import('./src/components/elements/image-element/ImageElementComponent.vue')['default']
    PagePreviewComponent: typeof import('./src/components/PagePreviewComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextElementComponent: typeof import('./src/components/elements/text-element/TextElementComponent.vue')['default']
  }
}
